import type { NextPage } from "next";
import Head from "next/head";
import VideoBackground from "../components/Background/VideoBackground";
import Content from "../components/Content/Content";
import { GlassmorphismBackdrop } from "../components/Glassmorphism/Glassmorphism.styled";
import PostModal from "../components/Modal/PostModal/PostModal";
import Nav from "../components/Nav/Nav";
import { useAppSelector } from "../hooks/hooks";
import { selectIsOpen } from "../store/modal/modalSlice";
import { getPosts, selectPostList } from "../store/post/postSlice";
import { wrapper } from "../store/store";

const Home: NextPage = () => {
  const postList = useAppSelector(selectPostList);
  const isOpen = useAppSelector(selectIsOpen);

  console.log(postList);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PostModal isOpen={isOpen} />
      <div style={{ position: "relative" }}>
        <VideoBackground />
        <GlassmorphismBackdrop />
      </div>
      <Nav />
      <main style={{ width: "100%", height: "100%" }}>
        <Content />
      </main>
    </>
  );
};

Home.getInitialProps = wrapper.getInitialPageProps(
  ({ dispatch }) =>
    async () => {
      await dispatch(getPosts());
    }
);

export default Home;
