import type { NextPage } from "next";
import react, { useEffect } from "react";
import Head from "next/head";
import Content from "../components/Content/Content";
import Layout from "../components/Layout/Layout";
import PostModal from "../components/Modal/PostModal/PostModal";
import { useAppDispatch, useAppSelector } from "../hooks/hooks";
import { selectIsOpen } from "../store/modal/modalSlice";
import { getPosts } from "../store/post/postSlice";
import { wrapper } from "../store/store";

const Home: NextPage = () => {
  const isOpen = useAppSelector(selectIsOpen);
  const dispatch = useAppDispatch();

  useEffect(() => {
    dispatch(getPosts());
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PostModal isOpen={isOpen} />
      <Layout>
        <Content />
      </Layout>
    </>
  );
};

// Home.getInitialProps = wrapper.getInitialPageProps(
//   ({ dispatch }) =>
//     async () => {
//       await dispatch(getPosts());
//     }
// );

export default Home;
